In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\shwet\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\shwet\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\shwet\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\shwet\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in C:\Users\shwet\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

### Pandas is used for the data manipulation task

In [2]:
import numpy as np
import pandas as pd

### Series:- It is basically a single column or row the dimension of series will be 1d so this is how we identify series
### dataframe:- it is a collection or combination of more than one series

# SERIES

In [1]:
import numpy as np
import pandas as pd

In [3]:
a=pd.Series([12,45,67])
print(a)
print(type(a))

0    12
1    45
2    67
dtype: int64
<class 'pandas.Series'>

### How to create series using numpy array

In [6]:
arr1=np.array([1,2,3,4,5,6,7])
print(arr1.ndim)
print(type(arr1))

1
<class 'numpy.ndarray'>

In [7]:
s=pd.Series(arr1)
print(type(s))
print(s)

<class 'pandas.Series'>
0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int64

### How to create series from dictionary

In [9]:
di={"marks":[20,30,40,50,60]}

In [11]:
s=pd.Series(di)
print(s)
print(type(s))

marks    [20, 30, 40, 50, 60]
dtype: object
<class 'pandas.Series'>

se=pd.Series([10,12,34,56])
print(se)
print()
print(type(se))
print(se.size)
print(se.shape)
print(se.ndim)
print(se.dtype)

### How to give name to series

In [16]:
se=pd.Series([12,4,34,56,7,8,65],name='markss')
print(se)

0    12
1     4
2    34
3    56
4     7
5     8
6    65
Name: markss, dtype: int64

### How to give custom indexing

In [17]:
se=pd.Series([12,4,34,56,7,8,65],index=['a','b','c','d','e','f','g'])
print(se)

a    12
b     4
c    34
d    56
e     7
f     8
g    65
dtype: int64

In [18]:
s=pd.Series([56,32,97,84,71],index=['shweta','pihu','pranjal','riya','ayushi'])
print(s)

shweta     56
pihu       32
pranjal    97
riya       84
ayushi     71
dtype: int64

# DAT

### How to create dataframe from dictionary

In [21]:
d={
    'eng':[14,34,32,26],
    'hindi':[34,66,77,89],
    'Python':[23,21,34,54]
}
df=pd.DataFrame(d,index=['shweta','pihu','pranjal','riya'])
# print(df)
display(df)

         eng  hindi  Python
shweta    14     34      23
pihu      34     66      21
pranjal   32     77      34
riya      26     89      54

In [1]:
import pandas as pd
import numpy as np

In [4]:
d={ 'eng':[20,30,40,50,60],
    'hindi':[32,12,54,32,53],
    'maths':[23,62,62,29,87],
    'science':[83,74,59,32,32]
  }
df=pd.DataFrame(d,index=['A','B','C','D','E'])
# print(df)
display(df)

   eng  hindi  maths  science
A   20     32     23       83
B   30     12     62       74
C   40     54     62       59
D   50     32     29       32
E   60     53     87       32

# How to loadexternal dataset in pandas

In [6]:
data = pd.read_excel(r"C:\Users\shwet\Downloads\pandas 4000 data.xlsx")

In [7]:
df=pd.DataFrame(data)
display(df)

,Person ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,1,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,11,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,6,ES-2013-1579342,2013-01-28,2013-01-30,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,6,SG-2013-4320,2013-11-05,2013-11-06,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
658,10,ES-2012-4934238,2012-02-02,2012-02-05,First Class,JH-15820,John Huston,Consumer,Hamburg,Hamburg,...,TEC-PH-10004910,Technology,Phones,"Samsung Signal Booster, Full Size",965.160,7,0.0,463.2600,253.09,High
659,10,IT-2013-5930911,2013-03-19,2013-03-19,Same Day,MV-17485,Mark Van Huff,Consumer,Saint-Chamond,Rhône-Alpes,...,OFF-ST-10000288,Office Supplies,Storage,"Fellowes Lockers, Industrial",748.116,4,0.1,282.5160,253.03,Critical
660,6,ES-2012-2674466,2012-03-21,2012-03-23,Second Class,JW-15955,Joni Wasserman,Consumer,Fontenay-aux-Roses,Ile-de-France,...,FUR-BO-10004844,Furniture,Bookcases,"Sauder Corner Shelving, Mobile",943.866,7,0.1,209.7060,252.90,Critical
661,12,IN-2014-54708,2014-05-24,2014-05-29,Second Class,LA-16780,Laura Armstrong,Corporate,Baotou,Inner Mongolia,...,FUR-BO-10001822,Furniture,Bookcases,"Dania Library with Doors, Metal",1447.440,4,0.0,43.3200,252.36,Medium
662,10,ES-2013-5085939,2013-06-14,2013-06-16,First Class,FM-14215,Filia McAdams,Corporate,Prato,Tuscany,...,TEC-AC-10003265,Technology,Accessories,"Belkin Router, Bluetooth",1552.500,6,0.0,62.1000,252.17,Medium

# Data Analysis and inception

### Information

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 663 entries, 0 to 662
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Person ID       663 non-null    int64
 1   Order ID        663 non-null    str
 2   Order Date      663 non-null    datetime64[us]
 3   Ship Date       663 non-null    datetime64[us]
 4   Ship Mode       663 non-null    str
 5   Customer ID     663 non-null    str
 6   Customer Name   663 non-null    str
 7   Segment         663 non-null    str
 8   City            663 non-null    str
 9   State           663 non-null    str
 10  Country         663 non-null    str
 11  Postal Code     130 non-null    float64
 12  Market          663 non-null    str
 13  Region          663 non-null    str
 14  Product ID      663 non-null    str
 15  Category        663 non-null    str
 16  Sub-Category    663 non-null    str
 17  Product Name    663 non-null    str
 18  Sales           663 non-null    float64
 19  Quantity        663 non-null    int64
 20  Discount        663 non-null    float64
 21  Profit          663 non-null    float64
 22  Shipping Cost   663 non-null    float64
 23  Order Priority  663 non-null    str
dtypes: datetime64[us](2), float64(5), int64(2), str(15)
memory usage: 230.9 KB

In [10]:
df.shape

(663, 24)

In [11]:
df.size

15912

### How to load csv data set

In [12]:
data=pd.read_csv(r"C:\Users\shwet\Downloads\customers-1000.csv")

In [13]:
df=pd.DataFrame(data)
print(df)

     Index      Customer Id First Name Last Name                      Company  \
0        1  dE014d010c7ab0c     Andrew   Goodman                Stewart-Flynn
1        2  2B54172c8b65eC3      Alvin      Lane  Terry, Proctor and Lawrence
2        3  d794Dd48988d2ac      Jenna   Harding                 Bailey Group
3        4  3b3Aa4aCc68f3Be   Fernando      Ford                 Moss-Maxwell
4        5  D60df62ad2ae41E       Kara     Woods              Mccarthy-Kelley
..     ...              ...        ...       ...                          ...
995    996  FbcCaF483aFaFAE      Diana    Monroe                  Bass-Wilson
996    997  979c4D58Ae9a9cc      Jerry   Morales                   Pratt-King
997    998  D0DcF6a4BcefCc8     Tracie     Floyd     Holt, Wilson and Shields
998    999  90EE9CbbDa374E9       Paul    Barnes     Brown, Oliver and Haynes
999   1000  51732B5b2328015    Dominic     Duran                   Durham LLC

                     City                                            Country  \
0             Rowlandberg                                              Macao
1                Bethside                                   Papua New Guinea
2            Moniquemouth                                              China
3              Leeborough                                              Macao
4        Port Jacksonland                                              Nepal
..                    ...                                                ...
995     Lake Jacksonmouth                                          Guatemala
996  South Dominiquemouth                                            Georgia
997       East Chloeshire                                    Solomon Islands
998           South Shane                                            Finland
999            East Wendy  British Indian Ocean Territory (Chagos Archipe...

                   Phone 1                Phone 2  \
0        846-790-4623x4715    (422)787-2331x71127
1       124-597-8652x05682      321.441.0588x6218
2       (335)987-3085x3780       001-680-204-8312
3            (047)752-3122      048.779.5035x9122
4    +1-360-693-4419x19272           163-627-2565
..                     ...                    ...
995  +1-171-715-9766x54993    (489)413-7296x32807
996       132.253.8501x097  +1-301-292-8363x80270
997             1193982387          (482)926-8966
998   +1-537-466-3245x3699           791-835-9075
999        +1-278-758-4331       814-860-0941x057

                             Email Subscription Date  \
0    marieyates@gomez-spencer.info        2021-07-26
1            alexandra86@mccoy.com        2021-06-24
2          justincurtis@pierce.org        2020-04-05
3              adeleon@hubbard.org        2020-11-29
4            jesus90@roberson.info        2022-04-22
..                             ...               ...
995     cassidymercado@bonilla.com        2022-01-09
996        gavin13@logan-downs.com        2021-08-21
997         lowehailey@oconnor.org        2020-04-22
998   hodgeseddie@hardin-wells.com        2021-03-12
999         owarner@velasquez.info        2021-12-09

                          Website
0            http://www.shea.biz/
1       http://www.pena-cole.com/
2     http://www.booth-reese.biz/
3          http://www.hebert.com/
4             http://merritt.com/
..                            ...
995            http://castro.net/
996       https://www.braun.info/
997  http://www.zavala-rubio.com/
998  https://stone-randolph.info/
999           http://www.cox.com/

[1000 rows x 12 columns]

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              1000 non-null   int64
 1   Customer Id        1000 non-null   str
 2   First Name         1000 non-null   str
 3   Last Name          1000 non-null   str
 4   Company            1000 non-null   str
 5   City               1000 non-null   str
 6   Country            1000 non-null   str
 7   Phone 1            1000 non-null   str
 8   Phone 2            1000 non-null   str
 9   Email              1000 non-null   str
 10  Subscription Date  1000 non-null   str
 11  Website            1000 non-null   str
dtypes: int64(1), str(11)
memory usage: 244.8 KB

In [16]:
df.size

12000

In [17]:
df.shape

(1000, 12)

### Exploring and reading data

In [3]:
d={
    'eng':[14,34,32,26,34],
    'hindi':[34,66,77,89,32],
    'Python':[23,21,34,54,73]
}
df=pd.DataFrame(d,index=['A','B','C','D','E'])
# print(df)
display(df)

   eng  hindi  Python
A   14     34      23
B   34     66      21
C   32     77      34
D   26     89      54
E   34     32      73

### to save the datframe in excel format

In [4]:
df.to_excel("shweta_file_created.xlsx")

In [7]:
# to ignore index in the file
df.to_excel("ignore_indexes.xlsx",index=False)

In [9]:
data=pd.read_excel(r"C:\Users\shwet\Downloads\pandas 4000 data.xlsx")

In [10]:
df=pd.DataFrame(data)

In [16]:
# by default bina value ke 5 rows starting ke
df.head(3)

,Person ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,1,CA-2012-124891,2012-07-31,2012-07-31,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,1,IN-2013-77878,2013-02-05,2013-02-07,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,11,IN-2013-71249,2013-10-17,2013-10-18,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium

In [49]:
# by default bina value ke 5 rows last ke
df.tail(3)

      id name   age
2  103.0  NaN  12.0
3  104.0   CC   NaN
4    NaN  NaN  67.0

In [19]:
# total columns
df.columns

Index(['Person ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'City', 'State', 'Country',
       'Postal Code', 'Market', 'Region', 'Product ID', 'Category',
       'Sub-Category', 'Product Name', 'Sales', 'Quantity', 'Discount',
       'Profit', 'Shipping Cost', 'Order Priority'],
      dtype='str')

In [20]:
df.index

RangeIndex(start=0, stop=663, step=1)

In [23]:
display(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 663 entries, 0 to 662
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Person ID       663 non-null    int64
 1   Order ID        663 non-null    str
 2   Order Date      663 non-null    datetime64[us]
 3   Ship Date       663 non-null    datetime64[us]
 4   Ship Mode       663 non-null    str
 5   Customer ID     663 non-null    str
 6   Customer Name   663 non-null    str
 7   Segment         663 non-null    str
 8   City            663 non-null    str
 9   State           663 non-null    str
 10  Country         663 non-null    str
 11  Postal Code     130 non-null    float64
 12  Market          663 non-null    str
 13  Region          663 non-null    str
 14  Product ID      663 non-null    str
 15  Category        663 non-null    str
 16  Sub-Category    663 non-null    str
 17  Product Name    663 non-null    str
 18  Sales           663 non-null    float64
 19  Quantity        663 non-null    int64
 20  Discount        663 non-null    float64
 21  Profit          663 non-null    float64
 22  Shipping Cost   663 non-null    float64
 23  Order Priority  663 non-null    str
dtypes: datetime64[us](2), float64(5), int64(2), str(15)
memory usage: 230.9 KB

None

In [48]:
d={
    'id':[np.nan,102,103,104,np.nan],
    'name':['AA','BB',np.nan,'CC',np.nan],
    'age':[23,np.nan,12,np.nan,67]
}
df=pd.DataFrame(d)
df

      id name   age
0    NaN   AA  23.0
1  102.0   BB   NaN
2  103.0  NaN  12.0
3  104.0   CC   NaN
4    NaN  NaN  67.0

### to find misiing value in pandas

In [45]:
display(df.isna())   ## it tells true where nan values found and other false

      id   name    age
0   True  False  False
1  False  False   True
2  False   True  False
3  False  False   True
4   True   True  False

In [44]:
display(df.isna().sum())  # it tells total nan values for each column

id      2
name    2
age     2
dtype: int64

In [47]:
display(df.isna().sum().sum())  ## it tells total no. of nan values of whole dataset

np.int64(6)

In [50]:
data=pd.read_excel(r"C:\Users\shwet\Downloads\pandas 4000 data.xlsx")
8i

In [51]:
df=pd.DataFrame(data)

In [52]:
df.isna().sum()

Person ID           0
Order ID            0
Order Date          0
Ship Date           0
Ship Mode           0
Customer ID         0
Customer Name       0
Segment             0
City                0
State               0
Country             0
Postal Code       533
Market              0
Region              0
Product ID          0
Category            0
Sub-Category        0
Product Name        0
Sales               0
Quantity            0
Discount            0
Profit              0
Shipping Cost       0
Order Priority      0
dtype: int64

In [53]:
df.isna().sum().sum()

np.int64(533)